import * as fs from "node:fs";
import type { AgentEvent } from "@oh-my-pi/pi-agent-core";
import type { ToolCall } from "@oh-my-pi/pi-ai";
import { isEnoent, logger } from "@oh-my-pi/pi-utils";
import type { Settings } from "../config/settings";
import { normalizeDiff, normalizeToLF, ParseError, previewPatch, stripBom } from "../edit";
import type { SecretObfuscator } from "../secrets/obfuscator";
import { assertEditableFile } from "../tools/auto-generated-guard";
import { ToolError } from "../tools/tool-errors";

/**
 * Dependencies the {@link StreamingEditGuard} needs from its owning session.
 */
export interface StreamingEditGuardContext {
	settings: Settings;
	abortAgent(): void;
	resolveFsPath(filePath: string): string | undefined;
	getCwd(): string;
	getObfuscator(): SecretObfuscator | undefined;
}

interface StreamingEditCall {
	toolCall: ToolCall;
	path: string;
	resolvedPath: string;
	diff?: string;
	op?: string;
	rename?: string;
}

/**
 * Watches mid-stream `edit` tool calls and aborts the agent early when the
 * partial diff already proves the patch will fail (auto-generated file,
 * removed lines that don't exist in the target, malformed diff). Aborting
 * mid-stream saves the round-trip cost of waiting for a doomed tool call.
 */
export class StreamingEditGuard {
	#ctx: StreamingEditGuardContext;
	#abortTriggered = false;
	#checkedLineCounts = new Map<string, number>();
	#precheckedToolCallIds = new Set<string>();
	#fileCache = new Map<string, string>();
	#lastToolCallId: string | undefined;

	constructor(ctx: StreamingEditGuardContext) {
		this.#ctx = ctx;
	}

	/** Reset all per-turn state. Call on `turn_start`. */
	reset(): void {
		this.#abortTriggered = false;
		this.#checkedLineCounts.clear();
		this.#precheckedToolCallIds.clear();
		this.#fileCache.clear();
	}

	/**
	 * Pre-cache the target file's content (so {@link maybeAbort} can do
	 * line-existence checks without sync I/O on the hot path) and run the
	 * auto-generated-file guard once per tool-call id.
	 */
	preCache(event: AgentEvent): void {
		if (!this.#ctx.settings.get("edit.streamingAbort")) return;
		if (this.#abortTriggered) return;
		if (event.type !== "message_update") return;

		const assistantEvent = event.assistantMessageEvent;
		if (
			assistantEvent.type !== "toolcall_start" &&
			assistantEvent.type !== "toolcall_delta" &&
			assistantEvent.type !== "toolcall_end"
		) {
			return;
		}

		const streamingEdit = this.#getEditToolCall(event);
		if (!streamingEdit) return;

		const shouldCheckAutoGenerated =
			!streamingEdit.toolCall.id || !this.#precheckedToolCallIds.has(streamingEdit.toolCall.id);
		if (shouldCheckAutoGenerated) {
			if (streamingEdit.toolCall.id) {
				this.#precheckedToolCallIds.add(streamingEdit.toolCall.id);
			}
			this.#abortForAutoGeneratedPath(streamingEdit.toolCall, streamingEdit.path, streamingEdit.resolvedPath);
		}

		this.#ensureFileCache(streamingEdit.resolvedPath);
	}

	/**
	 * Inspect the partial diff after each toolcall delta/end and abort the
	 * agent if the patch is already provably broken.
	 */
	maybeAbort(event: AgentEvent): void {
		if (!this.#ctx.settings.get("edit.streamingAbort")) return;
		if (this.#abortTriggered) return;
		if (event.type !== "message_update") return;

		const assistantEvent = event.assistantMessageEvent;
		if (assistantEvent.type !== "toolcall_end" && assistantEvent.type !== "toolcall_delta") return;

		const streamingEdit = this.#getEditToolCall(event);
		if (
			streamingEdit?.toolCall.id === null ||
			streamingEdit?.toolCall.id === undefined ||
			streamingEdit?.toolCall.id === ""
		)
			return;

		const { toolCall, path, resolvedPath, diff, op, rename } = streamingEdit;
		if (diff === null || diff === undefined || diff === "") return;
		if (op !== null && op !== undefined && op !== "" && op !== "update") return;

		if (!diff.includes("\n")) return;
		const lastNewlineIndex = diff.lastIndexOf("\n");
		if (lastNewlineIndex < 0) return;
		const diffForCheck = diff.endsWith("\n") ? diff : diff.slice(0, lastNewlineIndex + 1);
		if (diffForCheck.trim().length === 0) return;

		let normalizedDiff = normalizeDiff(diffForCheck.replace(/\r/g, ""));
		if (!normalizedDiff) return;
		const obfuscator = this.#ctx.getObfuscator();
		if (obfuscator) normalizedDiff = obfuscator.deobfuscate(normalizedDiff);
		if (!normalizedDiff) return;
		const lines = normalizedDiff.split("\n");
		const hasChangeLine = lines.some(line => line.startsWith("+") || line.startsWith("-"));
		if (!hasChangeLine) return;

		const lineCount = lines.length;
		const lastChecked = this.#checkedLineCounts.get(toolCall.id);
		if (lastChecked !== undefined && lineCount <= lastChecked) return;
		this.#checkedLineCounts.set(toolCall.id, lineCount);

		const removedLines = lines
			.filter(line => line.startsWith("-") && !line.startsWith("--- "))
			.map(line => line.slice(1));
		if (removedLines.length > 0) {
			let cachedContent = this.#fileCache.get(resolvedPath);
			if (cachedContent === undefined) {
				this.#ensureFileCache(resolvedPath);
				cachedContent = this.#fileCache.get(resolvedPath);
			}
			if (cachedContent !== undefined) {
				const missing = removedLines.find(line => !cachedContent.includes(normalizeToLF(line)));
				if (missing !== null && missing !== undefined && missing !== "") {
					this.#abortTriggered = true;
					logger.warn("Streaming edit aborted due to patch preview failure", {
						toolCallId: toolCall.id,
						path,
						error: `Failed to find expected lines in ${path}:\n${missing}`,
					});
					this.#ctx.abortAgent();
				}
				return;
			}
			if (assistantEvent.type === "toolcall_delta") return;
			void this.#checkRemovedLinesAsync(toolCall.id, path, resolvedPath, removedLines);
			return;
		}

		if (assistantEvent.type === "toolcall_delta") return;
		void this.#checkPreviewPatchAsync(toolCall.id, path, rename, normalizedDiff);
	}

	/** Invalidate the cached content for a file once the edit completes. */
	invalidateForPath(filePath: string): void {
		const resolvedPath = this.#ctx.resolveFsPath(filePath);
		if (resolvedPath === undefined) return;
		this.#fileCache.delete(resolvedPath);
	}

	#getEditToolCall(event: AgentEvent): StreamingEditCall | undefined {
		if (event.type !== "message_update") return undefined;
		if (event.message.role !== "assistant") return undefined;

		const contentIndex = event.assistantMessageEvent.contentIndex ?? 0;
		const messageContent = event.message.content;
		if (!Array.isArray(messageContent) || contentIndex < 0 || contentIndex >= messageContent.length) {
			return undefined;
		}

		const block = messageContent[contentIndex];
		if (block?.type !== "toolCall" || block.name !== "edit") return undefined;
		const toolCall: ToolCall = block;

		const args = toolCall.arguments;
		if (!args || typeof args !== "object" || Array.isArray(args)) return undefined;
		if ("old_text" in args || "new_text" in args) return undefined;

		const path = typeof args.path === "string" ? args.path : undefined;
		if (path === null || path === undefined || path === "") return undefined;

		const resolvedPath = this.#ctx.resolveFsPath(path);
		if (resolvedPath === undefined) return undefined;

		return {
			toolCall,
			path,
			resolvedPath,
			diff: typeof args.diff === "string" ? args.diff : undefined,
			op: typeof args.op === "string" ? args.op : undefined,
			rename: typeof args.rename === "string" ? args.rename : undefined,
		};
	}

	#abortForAutoGeneratedPath(toolCall: ToolCall, path: string, resolvedPath: string): void {
		if (this.#lastToolCallId === toolCall.id) return;
		this.#lastToolCallId = toolCall.id;
		void assertEditableFile(resolvedPath, path).catch(error => {
			// peekFile and other I/O can reject with ENOENT, etc. Only ToolError means
			// auto-generated detection; other failures are left for the edit tool.
			if (!(error instanceof ToolError)) return;
			if (this.#lastToolCallId !== toolCall.id) return;

			if (!this.#abortTriggered) {
				this.#abortTriggered = true;
				logger.warn("Streaming edit aborted due to auto-generated file guard", {
					toolCallId: toolCall.id,
					path,
				});
				this.#ctx.abortAgent();
			}
		});
	}

	#ensureFileCache(resolvedPath: string): void {
		if (this.#fileCache.has(resolvedPath)) return;

		try {
			const rawText = fs.readFileSync(resolvedPath, "utf-8");
			const { text } = stripBom(rawText);
			this.#fileCache.set(resolvedPath, normalizeToLF(text));
		} catch {
			// Don't cache on read errors (including ENOENT) - let the edit tool handle them
		}
	}

	async #checkRemovedLinesAsync(
		toolCallId: string,
		path: string,
		resolvedPath: string,
		removedLines: string[],
	): Promise<void> {
		if (this.#abortTriggered) return;
		try {
			const { text } = stripBom(await Bun.file(resolvedPath).text());
			const normalizedContent = normalizeToLF(text);
			const missing = removedLines.find(line => !normalizedContent.includes(normalizeToLF(line)));
			if (missing !== null && missing !== undefined && missing !== "") {
				this.#abortTriggered = true;
				logger.warn("Streaming edit aborted due to patch preview failure", {
					toolCallId,
					path,
					error: `Failed to find expected lines in ${path}:\n${missing}`,
				});
				this.#ctx.abortAgent();
			}
		} catch (error) {
			if (!isEnoent(error)) {
				logger.debug("Streaming edit-guard removed-line check failed", {
					toolCallId,
					path,
					error: error instanceof Error ? error.message : String(error),
				});
			}
		}
	}

	async #checkPreviewPatchAsync(
		toolCallId: string,
		path: string,
		rename: string | undefined,
		normalizedDiff: string,
	): Promise<void> {
		if (this.#abortTriggered) return;
		try {
			await previewPatch(
				{ path, op: "update", rename, diff: normalizedDiff },
				{
					cwd: this.#ctx.getCwd(),
					allowFuzzy: this.#ctx.settings.get("edit.fuzzyMatch"),
					fuzzyThreshold: this.#ctx.settings.get("edit.fuzzyThreshold"),
				},
			);
		} catch (error) {
			if (error instanceof ParseError) return;
			this.#abortTriggered = true;
			logger.warn("Streaming edit aborted due to patch preview failure", {
				toolCallId,
				path,
				error: error instanceof Error ? error.message : String(error),
			});
			this.#ctx.abortAgent();
		}
	}
}
